spring:
  application:
    name: tangchenyipinye
  mvc:
    contentnegotiation:
      favor-parameter: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    suffix: .html
    encoding: utf-8
    content-type: text/html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.18.54.18:3306/addb?useUnicode=true&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
    url: jdbc:mysql://localhost:3306/addb?useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password: huang
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/tangchenyipinye/project/mapper/xml/*.xml
server:
  port: 8888


#  thymeleaf:
#    cache: false
#    suffix: .html
#    encoding: UTF-8
#    content-type: text/html